export default [
  {
    id: "1",
    avatarImage: require("../assets/Avatars/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpg"),
    avatarName: "Franklin",
    Post: require("../assets/Avatars/charles-deluvio-kVg2DQTAK7c-unsplash.jpg"),
    likedAvatar: require("../assets/Avatars/ben-parker-NohB3FJSY90-unsplash.jpg"),
    PostHeight: 400,
  },
  {
    id: "2",
    avatarImage: require("../assets/Avatars/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpg"),
    avatarName: "Franklin",
    Post: require("../assets/Avatars/charles-deluvio-kVg2DQTAK7c-unsplash.jpg"),
    likedAvatar: require("../assets/Avatars/ben-parker-NohB3FJSY90-unsplash.jpg"),
    PostHeight: 300,
  },
  {
    id: "3",
    avatarImage: require("../assets/Avatars/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpg"),
    avatarName: "Franklin",
    Post: require("../assets/Avatars/charles-deluvio-kVg2DQTAK7c-unsplash.jpg"),
    likedAvatar: require("../assets/Avatars/ben-parker-NohB3FJSY90-unsplash.jpg"),
    PostHeight: 500,
  },
  {
    id: "4",
    avatarImage: require("../assets/Avatars/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpg"),
    avatarName: "Franklin",
    Post: require("../assets/Avatars/charles-deluvio-kVg2DQTAK7c-unsplash.jpg"),
    likedAvatar: require("../assets/Avatars/ben-parker-NohB3FJSY90-unsplash.jpg"),
    PostHeight: 400,
  },
  {
    id: "5",
    avatarImage: require("../assets/Avatars/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpg"),
    avatarName: "Franklin",
    Post: require("../assets/Avatars/charles-deluvio-kVg2DQTAK7c-unsplash.jpg"),
    likedAvatar: require("../assets/Avatars/ben-parker-NohB3FJSY90-unsplash.jpg"),
    PostHeight: 300,
  },
  {
    id: "6",
    avatarImage: require("../assets/Avatars/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpg"),
    avatarName: "Franklin",
    Post: require("../assets/Avatars/charles-deluvio-kVg2DQTAK7c-unsplash.jpg"),
    likedAvatar: require("../assets/Avatars/ben-parker-NohB3FJSY90-unsplash.jpg"),
    PostHeight: 300,
  },
];
